language: node_js
node_js:
  - "stable"

cache:
  directories:
  - .cache

branches:
  only:
    - master

before_deploy: gatsby build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: adblock-thai/adblock-thai.github.io
  local_dir: ./public
  target_branch: master
  on:
    branch: master