language: node_js
node_js:
  - 12

dist: bionic

cache: npm

branches:
  only:
    - master

before_deploy:
  - "npm i -g gatsby"
  - "npm i"
  - "npm run test"
  - "npm run preDeploy"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: adblock-thai/adblock-thai.github.io
  local_dir: public
  keep-history: true
  target_branch : master
  on:
    branch: master
