language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

branches:
  only:
    - master

before_deploy:
  - "npm i -g gatsby"
  - "npm i"
  - "npm run test"


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: adblock-thai/adblock-thai.github.io
  local_dir: public
  keep-history: true
  on:
    branch: master
